# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19e4d17d6e39107c692b46af40a795037564fff51871af628cca47d10470811e25035b0d489fff83b42964ecaa001da1a648485f16c5addf215def798165d6f5

test:
  secret_key_base: 3f10a50d3058e149ecf0223dfe1df53b5b3e5767ea1dc222d6573e82b35460cd87412bf04bec4926accc5a16766d588cde5996b903974974012acac397b5b7ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
